{{- if .Values.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ieee9-grid.labels" (dict "ctx" . "component" "grid-central") | nindent 4 }}
spec:
  {{- with .Values.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingressHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grid-central
                port:
                  name: http
{{- end }}
